spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Spring_Boot_Mini_Project
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
