spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Spring_Boot_Mini_Project
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_db
    username: postgres

    password: database09

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
