spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Spring_Boot_Mini_Project
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    username: postgres
    password: 1111@2222@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8081



